GET http://127.0.0.1:8000/products/ HTTP/1.1

###
POST http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzMTk2NTA4LCJpYXQiOjE3NDMxOTYyMDgsImp0aSI6IjVhOWYxZjZlM2NhNTRhZDE5ZjNiZjZiNTFiY2VhZGQ5IiwidXNlcl9pZCI6Mn0.aFFuCRGYsBzpaNLcfbr0fJYzyaQfv3qM_efsEtngDjY

{
    "name": "Television",
    "price": 555.99,
    "stock": 10,
    "description": "An amazing new TV"
}

###
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "agnieszka",
    "password": "ThankYou-21"
}


###
GET http://127.0.0.1:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzMTk2NTA4LCJpYXQiOjE3NDMxOTYyMDgsImp0aSI6IjVhOWYxZjZlM2NhNTRhZDE5ZjNiZjZiNTFiY2VhZGQ5IiwidXNlcl9pZCI6Mn0.aFFuCRGYsBzpaNLcfbr0fJYzyaQfv3qM_efsEtngDjY
